export const CREATE_CHAT_REQUEST = "CREATE_CHAT_REQUEST";
export const CREATE_CHAT_SUCCESS = "CREATE_CHAT_SUCESS";
export const CREATE_CHAT_FAIL = "CREATE_CHAT_FAIL";
export const FIND_USER_CHATS_REQUEST = "FIND_USER_CHATS_REQUEST";
export const FIND_USER_CHATS_SUCCESS = "FIND_USER_CHATS_SUCCESS";
export const FIND_USER_CHATS_FAIL = "FIND_USER_CHATS_FAIL";
